name: ps_list
description: "A Dart package that allows you to retrieve a list of running processes and check whether a specific process is running on Linux, macOS, and Windows."
version: 0.0.3
repository: https://github.com/shakthizen/ps_list
homepage: https://github.com/shakthizen/ps_list

topics:
  - utility
  - process
  - task
  - list
  - processes

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.25.14
