name: ps_list
description: "Utilities for getting list of running processes"
version: 0.0.1

topics:
 - utility
 - process
 - task
 - windows
 - macos
 - linux

platforms:
  linux:
  macos:

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
